number=int(input("enter a number"))
number1=int(input("enter a number"))
print("sum=",number+number1,",Division",number/number1)
print("is number greater than number1?:",number>number1)
print(" are number and number1 equal",number==number1)
print("number greater than zero and number1 greater than zero",number>0 and number1>0)
print("logical AND:",number>0 and number1>0)
print("logical OR :",number>0 or number1<0)